# Generated by Django 5.1.4 on 2025-02-02 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGN', '0003_myuser_email_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
