# Generated by Django 5.1.4 on 2025-02-03 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGN', '0004_myuser_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email_verification_token',
            field=models.CharField(default='', max_length=255),
        ),
    ]
